---
title: "Benchmark binding of rows: 3 examples"
author: "John Malc (@dmpe)"
date: "September 7, 2015"
output: html_document
---

In order to run this benchmark, you must load this file: https://gist.github.com/dmpe/5aec87f0c7a5ae2115ca

```{r}
library("microbenchmark")
library("ggplot2")
library("RSocrata")
# source("https://gist.github.com/dmpe/5aec87f0c7a5ae2115ca")
set.seed(5125)
```

A smaller dataset.

```{r, echo=TRUE, eval=FALSE}
# https://github.com/hadley/dplyr/issues/1162#issuecomment-137870577
small <- microbenchmark(
  read.socrataRBIND("https://soda.demo.socrata.com/resource/4334-bgaj.csv"),
  read.socrataPLYR("https://soda.demo.socrata.com/resource/4334-bgaj.csv"),
  read.socrataDATATABLE("https://soda.demo.socrata.com/resource/4334-bgaj.csv"),
  times = 3L,
  unit = "s"
)

small
boxplot(small)

```

A large one.

```{r, echo=TRUE, eval=FALSE}

# 5878399 rows
# https://data.cityofchicago.org/resource/6zsd-86xi.csv
# 49142
# https://data.ny.gov/resource/hrvs-fxs2.csv
# 618029
# https://data.ny.gov/resource/cwsm-2ns3.json
bigger <- microbenchmark(
  read.socrataRBIND("https://data.ny.gov/resource/cwsm-2ns3.csv"),
  read.socrataPLYR("https://data.ny.gov/resource/cwsm-2ns3.csv"),
  read.socrataDPLYR("https://data.ny.gov/resource/cwsm-2ns3.csv"),
  read.socrataDATATABLE("https://data.ny.gov/resource/cwsm-2ns3.csv"),
  times = 3L,
  unit = "s"
)

bigger
boxplot(bigger)
```

Another one. 

```{r, echo=TRUE, eval=FALSE}
big <- microbenchmark(
  read.socrataRBIND("https://data.ny.gov/resource/hrvs-fxs2.csv"),
  read.socrataPLYR("https://data.ny.gov/resource/hrvs-fxs2.csv"),
  read.socrataDATATABLE("https://data.ny.gov/resource/hrvs-fxs2.csv"),
  times = 3L,
  unit = "s"
)

big
boxplot(big)

```

