---
title: "Vignette for RSocrata"
author: "Developers of the City of Chicago (USA)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(RSocrata)
```

### Example: Reading SoDA valid URLs
```{r}
earthquakesDataFrame <- read.socrata("http://soda.demo.socrata.com/resource/4334-bgaj.csv")
nrow(earthquakesDataFrame) # 1007 (two "pages")
class(earthquakesDataFrame$Datetime[1]) # POSIXlt
```

### Example: Reading "human-readable" URLs
```{r}
earthquakesDataFrame <- read.socrata("https://soda.demo.socrata.com/resource/4334-bgaj")
nrow(earthquakesDataFrame) # 1007 (two "pages")
class(earthquakesDataFrame$Datetime[1]) # POSIXlt
```

### Example: Using API key to read datasets
```{r}
token <- "ew2rEMuESuzWPqMkyPfOSGJgE"
earthquakesDataFrame <- read.socrata("http://soda.demo.socrata.com/resource/4334-bgaj.csv", app_token = token)
nrow(earthquakesDataFrame)
```

### Example: List all datasets on portal
```{r}
allSitesDataFrame <- ls.socrata("https://soda.demo.socrata.com")
nrow(allSitesDataFrame) # Number of datasets
allSitesDataFrame$title # Names of each dataset
```

### GEO & Leaflet

```{r}
# for geo support
library(leaflet)

geo_df <- read.socrataGEO("https://data.cityofchicago.org/resource/6zsd-86xi.geojson")

# OR classically
# library(geojsonio)
# geo_df <- geojsonio::geojson_read("https://data.cityofchicago.org/resource/6zsd-86xi.geojson", method = "local", parse = TRUE, what = "list")

m <- leaflet() %>%
  addGeoJSON(geo_df) %>%
  setView(-87.6, 41.8, zoom = 15) %>% 
  addTiles(attribution = paste(
    '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
    '&copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
  ))
m
```

